name: Sync Canvas assignments (ICS)

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch:         # allow manual run

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm init -y
      - run: npm install node-ical
      - name: Build assignments.json
        env:
          ICS_URL: ${{ secrets.CANVAS_ICS_URL }}
        run: node scripts/sync_ics.js
      - name: Commit updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/assignments.json
          git commit -m "Update assignments.json" || echo "No changes"
          git push
